version: '3.9'
services:
  web_gunicorn:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-y_h^@-1ixe3wyi6&+(1uaq04wejb1%r5lw@bq43+pcxlm2!02b
      - ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_NAME=mrb_db
      - DB_USER=mrb_user
      - DB_PASS=mrb_password123
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mrb_password123
      - POSTGRES_USER=mrb_user
      - POSTGRES_DB=mrb_db

  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web_gunicorn
volumes:
  postgres_data:
    driver: local