# Generated by Django 4.2 on 2023-05-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('organization_name', models.CharField(max_length=60, verbose_name='Organization name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('type_of_organization', models.CharField(choices=[('Restaurants', 'Restaurants'), ('Fast Food', 'Fast Food'), ('Coffee', 'Coffee'), ('Hotel', 'Hotel'), ('School', 'School'), ('Medical', 'Medical'), ('Pharmacy', 'Pharmacy'), ('Culture', 'Culture'), ('Corporate', 'Corporate'), ('Non Profit', 'Non Profit'), ('Individual', 'Individual'), ('Religious', 'Religious'), ('Business', 'Business'), ('Embassy', 'Embassy'), ('Night Life', 'Night Life')], max_length=30)),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=30, verbose_name='Confirm Password')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.location')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
