# Generated by Django 4.2 on 2023-05-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_location'),
        ('identity', '0002_remove_account_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.location'),
        ),
    ]
