# Generated by Django 4.2 on 2023-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=250, null=True),
        ),
    ]
