# Generated by Django 4.2 on 2023-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
