name: Deployment-dev (CD)
concurrency:
  group: development
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo "Deploy me"
